### ISSUE TITLE
Standard AWS env variable names

### ISSUE THREAD

**Issue by bkeroackdsc** [gdbtek/aws-tools#11]
The standard AWS environmental variables are AWS_ACCESS_KEY and AWS_SECRET_KEY (used by lots of 3rd party libs/tools). Would be nice to use those instead of forcing users to copy/paste ever time.

**Comment by gdbtek** [comment]
this tool has been updated to support AWS_ACCESS_KEY and AWS_SECRET_KEY. So with this, u don't need to copy and paste key over and over again.
